spring.application.name=StudyGroupFinderAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/StudyGroupFinder
spring.datasource.username=postgres
spring.datasource.password=My_DB_Password
spring.datasource.driver-class=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
